config/routes.rb
class WWWSubdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain == 'www')
  end
end

class Subdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain != 'www')
  end
end

SkyhqNew::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  authenticated :citizen do
    get '/' => 'blogit/posts#index'
  end

  # authenticated :super_admin do
  #   get '/' => 'blogit/posts#index'
  # end

  authenticated :business_user do
    get '/' => 'blogit/posts#index'
  end
  
  constraints(WWWSubdomain.new) do
    get '/' => 'general_pages#index'
  end

  constraints(Subdomain.new) do
    get '/' => Blogit::Engine
      # post "", to: "company_profiles#edit_post", as: "company_edit_post"
  end
  
  root :to => 'general_pages#index'

  match   "/post/save" => 'general_pages#save_post', :via => :post
  match   "/post/edit/:id" => 'general_pages#edit_post', :via => :put, as: "post_edit"

  post    "public/:id/tagline/", to: "company_profiles#save_tagline", as: "company_tagline"
  patch   "public/:id/edit/", to: "company_profiles#edit_post", as: "company_edit_post"
  delete  "public/:id", to: "general_pages#destroy_post", as: "delete_post"
  get "public", to: "blogit/posts#index"
  get '/get_citizens' => 'general_pages#get_citizen'
  get  '/home' => 'general_pages#index'
  get  '/about' => 'general_pages#about'
  get  '/contact' => 'general_pages#contact'
  get  '/faq' => 'general_pages#faq'
  get  '/testimonials' => 'general_pages#testimonials'
  get  '/pricing' => 'general_pages#pricing'
  get  '/services' => 'general_pages#services'
  get  '/tos' => 'general_pages#tos'
  post '/check-email' => 'general_pages#check_email'
  post '/check-subdomain' => 'general_pages#check_subdomain'
  get  '/edit_citizen_password' => 'blogit/posts#edit_citizen_password'
  post '/save_citizen_password' => 'blogit/posts#save_citizen_password'
  get  '/blog' => 'blogit/posts#index'

  post 'reply_comment/:post_id' => 'blogit/comments#create', :as => 'reply_comment'

  match '/posts/page/:page' => 'blogit/posts#index', :via => :get

  match '/posts' => 'blogit/posts#index', :via => :get

  get '/sticky_post' => 'conversations#sticky_post', :as => 'sticky_post'

  # get 'new_direct_message' => 'conversations#new_direct_message'
  # post 'direct_message' => 'conversations#direct_message', :as => 'direct_message'

  # post '/update_citizen_password' => 'blogit/posts#update_citizen_password'
  
  # match '/profile' => "company_profiles#admin_profile", :as => "admin_profile"
  # delete "/businesses/:business_id/managers/:id/delete", to: "managers#destroy", :as => "remove_manager"


  resources :manage_users
  
  resources :company_forums, :path => "comms" do
    resources :company_forum_topics do
      resources :forum_posts
    end
  end
  resources :company_docs, path: 'docs'

  resources :company_profiles

  resources :online_stores, :path => "orders" do
    resources :products
  end

  resources :categories, :path => "categories"

  resources :business_messengers, :path => "messengers"

  resources :locations do
    resources :managers 
    resources :employees
  end
  

  devise_for :citizens, :controllers => { 
    :omniauth_callbacks => "citizens/omniauth_callbacks",
    registrations: 'citizens/registrations',
    :sessions => 'user_authentications'
  }

  # devise_for :users

  devise_for :super_admins, controllers: { 
    registrations: 'super_admins/registrations'
    # ,
    # :sessions => 'user_authentications'
  }

  devise_for :business_users,:controllers => { 
    registrations: 'citizens/registrations'
  }

  devise_for :managers, skip: :sessions
  devise_for :staffs, skip: :sessions

  # devise_for :users, :controllers => { :sessions => :user_authentications, registrations: 'citizens/registrations'}
# devise_for :users, :skip => [:sessions]

  # devise_scope :super_admin do
  #   get "super_admins/login",    to: "devise/sessions#new"
  #   get "logout",   to: "devise/sessions#destroy"
  #   get "business/register", to: "devise/registrations#new"
  #   get "business/reset",    to: "devise/passwords#new"
  #   # get "business/profile", to: "devise/registrations#edit"
  # end

  devise_scope :citizen do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "reset",    to: "devise/passwords#new"
    get "profile", to: "devise/registrations#edit"
  end
  
  devise_scope :business_user do
    get "business/login", to: "devise/sessions#new", :as => 'business_login'
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "business/reset",    to: "devise/passwords#new"
    get "business/profile", to: "devise/registrations#edit", :as => 'business_profile'
  end

  get("/inbox/new/:super_admin_id", { :controller => "conversations", :action => 'new', :as => 'message_company'})

  get "sentbox", to: "conversations#sentbox", :as => 'sentbox'
  get "trashbox", to: "conversations#trashbox", :as => 'trashbox'
  
  resources :conversations, :path => "inbox", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= simple_form_for(@business, :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' } }) do |f| %>
<% if @business.errors.any? %>
<div id="error_explanation">
    <h4><%= pluralize(@business.errors.count, "error") %>prohibited this business from being saved:</h4>
    <ul>
        <% @business.errors.full_messages.each do |msg| %>
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
</div>
<% end %>
<form role="form">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zipcode %>
    <%= f.input :country %>
    <%= f.submit "Create Business Location", :class => "btn btn-primary" %>
</form>
<% end %>

app/views/businesses/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="well sidebar-nav">
                <ul class="nav">
                    <li>
                        Navigation
                    </li>
                    <li>
                        <%= link_to "Add business location".html_safe, new_business_path %>
                    </li>
                </ul>
            </div>
        </div>
        <!-- End Sidebar --><!-- Begin Content -->
        <div class="col-md-9">
            <div class="row margin-bottom-10">
                <%= gmaps4rails(@json) %>
                <% if @businesses.present? %>
                <div class="table-responsive">
                    <h3>Business Locations:</h3>
                    <table id="businesses" class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Address
                                </th>
                                <th>
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @businesses.each do |business| %>
                            <tr>
                                <td>
                                    <%= link_to "#{business.name}", business_path(business) %>
                                </td>
                                <td>
                                    <%= link_to "#{business.gmaps4rails_address}", business_path(business) %>
                                </td>
                                <td>
                                    <%= link_to "Edit" ,edit_business_path(business) %> | <%= link_to "Remove", business_path(business), :data => { :confirm => "Are you sure?" }, :method => :delete %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <% else %>
                <h3 class="text-center">
                Add up to 10 business locations. <%= link_to "Add a business location.".html_safe, new_business_path %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/businesses/new.html.erb
    <h3>New Business Location: </h3>
    <%= render 'form' %>
    <div class="smallMenuItems">
        <%= link_to 'Back', businesses_path %>
    </div>

app/views/businesses/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="well sidebar-nav">
                <ul class="nav">
                    <li>
                        Navigation
                    </li>
                    <li>
                        <%= link_to "Add Manager".html_safe, new_business_manager_path(@business) %>
                        <%= link_to 'Edit Location', edit_business_path(@business) %>
                    </li>
                </ul>
            </div>
        </div>
        <!-- End Sidebar --><!-- Begin Content -->
        <div class="col-md-9">
            <div class="row margin-bottom-10">
                <%= gmaps4rails(@json) %>
                <h3><b>Location Name: </b><%= @business.name %></h3>
                <h3><b>Location: </b><%= @business.gmaps4rails_address %></h3>
                <% unless @managers.nil? %>
                <h2 style="text-decoration:underline;">Managers</h2>
                <div class="table-responsive">
                    <table id="businesses" class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Title
                                </th>
                                <th>
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @managers.each do |manager| %>
                            <tr>
                                <td>
                                    <%= link_to "#{manager.name}", business_manager_path(@business, manager) %>
                                </td>
                                <td>
                                    <%= link_to "#{manager.title}", business_manager_path(@business, manager) %>
                                </td>
                                <td>
                                    <%= link_to "Cancel Manager's Account", business_manager_path(@business, manager), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => "btn btn-danger" %>
                                </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- <h2>Staff/Employees</h2> -->
                <ul>
                    <%# @employees.each do |employee| %>
                    <li>
                        <%#= link_to "#{employee.name}", business_employee_path(employee) %>
                    </li>
                    <%# end %>
                </ul>
                <div class="smallMenuItems">
                    <%= link_to 'Go Back', businesses_path, :class => "btn btn-warning" %>
                    <%#= link_to 'Create New Employee', new_business_employee_path(@business) %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>