config/routes.rb
class WWWSubdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain == 'www')
  end
end

class Subdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain != 'www')
  end
end

SkyhqNew::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  authenticated :citizen do
    get '/' => 'blogit/posts#index'
  end

  # authenticated :super_admin do
  #   get '/' => 'blogit/posts#index'
  # end

  authenticated :business_user do
    get '/' => 'blogit/posts#index'
  end
  
  constraints(WWWSubdomain.new) do
    get '/' => 'general_pages#index'
  end

  constraints(Subdomain.new) do
    get '/' => Blogit::Engine
      # post "", to: "company_profiles#edit_post", as: "company_edit_post"
  end
  
  root :to => 'general_pages#index'

  match   "/post/save" => 'general_pages#save_post', :via => :post
  match   "/post/edit/:id" => 'general_pages#edit_post', :via => :put, as: "post_edit"

  post    "public/:id/tagline/", to: "company_profiles#save_tagline", as: "company_tagline"
  patch   "public/:id/edit/", to: "company_profiles#edit_post", as: "company_edit_post"
  delete  "public/:id", to: "general_pages#destroy_post", as: "delete_post"
  get "public", to: "blogit/posts#index"
  get '/get_citizens' => 'general_pages#get_citizen'
  get  '/home' => 'general_pages#index'
  get  '/about' => 'general_pages#about'
  get  '/contact' => 'general_pages#contact'
  get  '/faq' => 'general_pages#faq'
  get  '/testimonials' => 'general_pages#testimonials'
  get  '/pricing' => 'general_pages#pricing'
  get  '/services' => 'general_pages#services'
  get  '/tos' => 'general_pages#tos'
  post '/check-email' => 'general_pages#check_email'
  post '/check-subdomain' => 'general_pages#check_subdomain'
  get  '/edit_citizen_password' => 'blogit/posts#edit_citizen_password'
  post '/save_citizen_password' => 'blogit/posts#save_citizen_password'
  get  '/blog' => 'blogit/posts#index'

  post 'reply_comment/:post_id' => 'blogit/comments#create', :as => 'reply_comment'

  match '/posts/page/:page' => 'blogit/posts#index', :via => :get

  match '/posts' => 'blogit/posts#index', :via => :get

  get '/sticky_post' => 'conversations#sticky_post', :as => 'sticky_post'

  # get 'new_direct_message' => 'conversations#new_direct_message'
  # post 'direct_message' => 'conversations#direct_message', :as => 'direct_message'

  # post '/update_citizen_password' => 'blogit/posts#update_citizen_password'
  
  # match '/profile' => "company_profiles#admin_profile", :as => "admin_profile"
  # delete "/businesses/:business_id/managers/:id/delete", to: "managers#destroy", :as => "remove_manager"


  resources :manage_users
  
  resources :company_forums, :path => "comms" do
    resources :company_forum_topics do
      resources :forum_posts
    end
  end
  resources :company_docs, path: 'docs'

  resources :company_profiles

  resources :online_stores, :path => "orders" do
    resources :products
  end

  resources :categories, :path => "categories"

  resources :business_messengers, :path => "messengers"

  resources :locations do
    resources :managers 
    resources :employees
  end
  

  devise_for :citizens, :controllers => { 
    :omniauth_callbacks => "citizens/omniauth_callbacks",
    registrations: 'citizens/registrations',
    :sessions => 'user_authentications'
  }

  # devise_for :users

  devise_for :super_admins, controllers: { 
    registrations: 'super_admins/registrations'
    # ,
    # :sessions => 'user_authentications'
  }

  devise_for :business_users,:controllers => { 
    registrations: 'citizens/registrations'
  }

  devise_for :managers, skip: :sessions
  devise_for :staffs, skip: :sessions

  # devise_for :users, :controllers => { :sessions => :user_authentications, registrations: 'citizens/registrations'}
# devise_for :users, :skip => [:sessions]

  # devise_scope :super_admin do
  #   get "super_admins/login",    to: "devise/sessions#new"
  #   get "logout",   to: "devise/sessions#destroy"
  #   get "business/register", to: "devise/registrations#new"
  #   get "business/reset",    to: "devise/passwords#new"
  #   # get "business/profile", to: "devise/registrations#edit"
  # end

  devise_scope :citizen do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "reset",    to: "devise/passwords#new"
    get "profile", to: "devise/registrations#edit"
  end
  
  devise_scope :business_user do
    get "business/login", to: "devise/sessions#new", :as => 'business_login'
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "business/reset",    to: "devise/passwords#new"
    get "business/profile", to: "devise/registrations#edit", :as => 'business_profile'
  end

  get("/inbox/new/:super_admin_id", { :controller => "conversations", :action => 'new', :as => 'message_company'})

  get "sentbox", to: "conversations#sentbox", :as => 'sentbox'
  get "trashbox", to: "conversations#trashbox", :as => 'trashbox'
  
  resources :conversations, :path => "inbox", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  helper_method :mailbox, :conversation
  before_filter :find_user_active
  
  def index
  end

  def new
    if params[:user_id].present?
      @user = BusinessUser.find(params[:user_id])
    end
    Conversation.new
    respond_to do |format|
      format.html
    end
  end

  def show
    current_user.mailbox
    respond_to do |format|
      format.html
    end
  end

  def create
    recipient_email = conversation_params(:recipient).split(',') if conversation_params(:recipient)
    if conversation_params(:user_id)
      recipient = conversation_params(:user_id).split(',').map{ |d| d.strip.gsub('@','') }
    elsif recipient_email
      recipient = Citizen.find_by(email: recipient_email)
    else
      recipient = Citizen.find_by(subdomain: request.subdomain)
    end

    recipient = Citizen.where("subdomain in (?) or email = ?", recipient, recipient_email) if conversation_params(:user_id)
    cc = Citizen.where("subdomain in (?) or email = ?", conversation_params(:cc).split(',').map{ |d| d.strip.gsub('@','') }, recipient_email) if conversation_params(:cc)
    recipient ||= SuperAdmin.find_by(email: recipient_email)

    if conversation_params(:user_id)
      recipient.map{|recipient|
        send_to = [recipient, cc].flatten
        conversation = current_user.send_message(send_to, *conversation_params(:body, :subject, :attachment)).conversation
      }
      @recipient_name = recipient.map{|recipient| recipient.name}
    else
      params[:conversation][:body] = params[:body_message].first if params[:body_message]
      conversation = current_user.send_message(recipient, *conversation_params(:body, :subject)).conversation
    end
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Message sent successfully.' }
      format.js{
        flash[:notice] = "Message sent successfully"
      }
    end
  end

  def reply
    @conversation_reply = current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    # respond_to do |format|
    #   format.html {redirect_to :back, notice: "Message sent successfully."}
    #   # format.js{@conversation_reply}
    #   format.js{redirect_to :back, notice: "Message sent successfully."}
    # end
    redirect_to :back, notice: "Message sent successfully."
  end

  def trash
    conversation.move_to_trash(@access)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(@access)
    redirect_to :conversations
  end

  def sticky_post;end

  def sentbox;end

  def trashbox;end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end

  private
    def find_user_active
      @access = current_user
      redirect_to root_url unless @access
    end
end

app/views/conversations/_comment_conversation_form.html.erb
<div class='row'>
    <div class='col-md-12 comment-reply'>

        <%#= link_to "Reply", "#", class: 'btn btn-success pull-right link-reply', style: "margin-top: -10px; margin-bottom: 10px;" %>
        <%= simple_form_for(:conversation, url: :conversations, remote: true, :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' } }) do |f| %>
        <form role="form">
            
            <div class="smallMenuItems">
                <%#= f.submit "Reply", class: 'btn btn-success pull-right btn_reply', :style => "display: none;" %>
            </div>

            <% if recipient.present? %>
                <%= f.hidden_field :recipient, :value => recipient.email %>
            <% end %>
            <div class="form-group">
                <%= f.hidden_field :subject, value: title %>
            </div>
            <div class="form-group">
                <%= f.text_area :body, :rows => 3, :class => "form-control", placeholder: "MESSAGE CONTENT", :style => 'display: none;' %>
            </div>
        </form>
        <% end %>
    </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.link-reply').each(function(){
      $(this).click(function(e){
        $(this).hide();
        $(this).parent('.comment-reply').find('form.conversation textarea').show();
        $(this).parent('.comment-reply').find('form.conversation .btn_reply').show();
        e.preventDefault();
      });
    });
  });
</script>

app/views/conversations/_conversation.html.erb
<%= content_tag_for(:li, conversation) do |conversation| %>
 
    <%= link_to conversation.subject, conversation %>
    <%#= link_to conversation.receipts_for(current_user).last.message.subject, conversation %>
    <%# if conversation.is_completely_trashed?(current_user) %>
      <%#= button_to 'Untrash', [:untrash, conversation], method: :post %>
    <%# else %>
      <%#= button_to 'Move to trash', [:trash, conversation], method: :post %>
    <%# end %>
  
<% end %>

app/views/conversations/_inbox_reply_form.html.erb
<div class='row'>
    <!-- <div class='col-md-1'>
        <%# image = commentor.avatar.blank? ? "img/profile-placeholder.png" : commentor.avatar.url %>
        <%#= image_tag image , :height => "52", :width => "52" %>
    </div> -->
    <div class='col-md-12 comment-reply'>
        
        <%= simple_form_for(:message, url: reply_conversation_path(conversation), :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :"data-id" => conversation.id, :class => 'form-control' } }) do |f| %>
        <form role="form">
          <div class="smallMenuItems">
            <%= f.submit "Reply", class: 'btn btn-success pull-right btn_reply', :"data-id" => conversation.id %>
          </div>
          <br />
          <div class="form-group">
              <%= f.hidden_field :subject, value: title %>
          </div>
          <div class="form-group">
            <%#= f.text_area :body, :rows => 1, :class => "form-control", placeholder: "MESSAGE CONTENT", :onkeypress=>"return replyInbox(this, event);", :"data-id" => conversation.id %>
            <%= f.text_area :body, :rows => 1, :class => "form-control", placeholder: "MESSAGE CONTENT", :"data-id" => conversation.id %>
          </div>
        </form>
        <% end %>
    </div>
</div>

app/views/conversations/_mail_inbox.html.erb
<% current_user.mailbox.inbox.each do |conversation| %>
  <% other_user = (conversation.messages.collect(&:sender) - [current_user]).first %>
  <% conversation.messages.limit(3).group_by(&:subject).each do |conversations, messages| %>

    <%# messages.each do |message| %>
      <% user = messages.map{ |m| m.sender} %>
      <%# url = user.avatar.blank? ? "img/profile-placeholder.png" : user.avatar.url %>
      <%= link_to("/inbox/#{conversation.id}") do%>
        <div class="col-md-12 message-list">
          <div class="col-md-3">
            <h4>
              <%#= message.subject %>
              <% counter = (messages.map{|user| user.sender.subdomain}.count > 1) ? "(#{messages.map{|user| user.sender.subdomain}.count})" : nil %>
              <%= messages.map{|user| user.sender.subdomain}.uniq.map(&:inspect).join(',').gsub('"','') %>
              <small><%= counter %></small>
            </h4>
          </div>
          <div class="col-md-7">
            <%#= truncate(messages.first.body, length: 100) %>
            <%= messages.first.subject %>
          </div>
          <div class="col-md-2">
            <i class="fa fa-clock-o"></i> <%= time_ago_in_words(messages.first.created_at) %>
          </div>
        </div>
      <% end %>
    <%# end %>
  <% end %>
<% end %>

app/views/conversations/_mail_sentbox.html.erb
<% current_user.mailbox.sentbox.each do |conversation| %>
  <% other_user = (conversation.messages.collect(&:sender) - [current_user]).first %>
  <% conversation.messages.limit(3).reverse.each do |message| %>
    <% user = message.sender %>
    <% url = user.avatar.blank? ? "img/profile-placeholder.png" : user.avatar.url %>
    <%= link_to("/inbox/#{conversation.id}") do%>
      <div class="col-md-12 message-list">
        <div class="col-md-3">
          <h4>
            <%= message.subject %>
            <small><%= user.subdomain %></small>
          </h4>
        </div>
        <div class="col-md-7">
          <%= truncate(message.body, length: 100) %>
        </div>
        <div class="col-md-2">
          <i class="fa fa-clock-o"></i> <%= time_ago_in_words(message.created_at) %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/conversations/_mail_trashbox.html.erb
<% current_user.mailbox.trash.each do |conversation| %>
  <% other_user = (conversation.messages.collect(&:sender) - [current_user]).first %>
  <% conversation.messages.limit(3).reverse.each do |message| %>
    <% user = message.sender %>
    <% url = user.avatar.blank? ? "img/profile-placeholder.png" : user.avatar.url %>
    <%= link_to("/inbox/#{conversation.id}") do%>
      <div class="col-md-12 message-list">
        <div class="col-md-3">
          <h4>
            <%= message.subject %>
            <small><%= user.subdomain %></small>
          </h4>
        </div>
        <div class="col-md-7">
          <%= truncate(message.body, length: 100) %>
        </div>
        <div class="col-md-2">
          <i class="fa fa-clock-o"></i> <%= time_ago_in_words(message.created_at) %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/conversations/_new_direct_message.html.erb
<h4><strong>Direct Message</strong></h4>
<br>
<% show_cancel = show_cancel.nil? ? true : false %>
<%= simple_form_for(:conversation, url: :conversations, :defaults => { :wrapper_html => {:class => 'form-group'}, :input_html => { :class => 'form-control' } }) do |f| %>
    <form role="form">
    <div class="form-group">
        <%= f.label :recipient %>
        <%= text_field_tag :to_user, nil, :class => "form-control", :value => "#{request.subdomain}", :readonly => true %>
    </div>

    <div class="form-group">
        <%= f.text_field :subject, :class => "form-control", placeholder: "TOPIC" %>
    </div>
    <div class="form-group">
        <%= text_area :body_message, nil, :rows => 7, :class => "form-control", placeholder: "POST MESSAGE" %>
    </div>
    <div class="smallMenuItems">
        <%= f.submit "SEND MESSAGE", class: 'btn btn-success' %>
        <% if show_cancel %>
            <%= link_to 'CANCEL', :back, class: 'btn btn-warning' %>
        <% end %>
    </div>
</form>
<% end %>

app/views/conversations/create.js.erb
$('.simple_form.conversation').trigger('reset');

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="col-sm-2">
        <ul>
          <li class="inbox-msg"><%= link_to "ComposeMessage", "#", class: "btn btn-primary", :style => "margin-bottom: 20px;", :id => "show-message" %></li>
          <li class="inbox-msg"><%= link_to "Sent", "#" %></li>
          <li class="inbox-msg"><%= link_to "Trash", "#" %></li>
        </ul>
      </div>
      <div class="col-sm-10">
        <h2 style="margin: 1px 0 2px 120px;">General Message <small>showing all message</small></h2>
        <br/>
        <div id="compose-message" hidden="true">
          <%= render "conversations/form" %>
        </div>
        <% current_user.mailbox.inbox.each do |conversation| %>
          <% other_user = (conversation.messages.collect(&:sender) - [current_user]).first %>
          <% conversation.messages.limit(3).reverse.each do |message| %>
            <% user = message.sender %>
            <% url = user.avatar.blank? ? "img/profile-placeholder.png" : user.avatar.url %>
            <%= link_to("/inbox/#{conversation.id}") do%>
              <div class="col-md-12 message-list">
                <div class="col-md-3">
                  <h4>
                    <%= message.subject %>
                    <small><%= user.subdomain %></small>
                  </h4>
                </div>
                <div class="col-md-7">
                  <%= truncate(message.body, length: 100) %>
                </div>
                <div class="col-md-2">
                  <i class="fa fa-clock-o"></i> <%= time_ago_in_words(message.created_at) %>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(e){
    $("#show-message").click(function(){
      $("#compose-message").toggle();
      e.preventDefault();
    });
  })
</script>

app/views/conversations/new.html.erb
<center>
  <h1 style="font-weight: bold;">
  	Compose Message
  </h1>
  <small style="font-size: 14px; color: rgb(150,150,150);">
  		Write your message here
  </small>
</center>
<div style="background-color: rgba(255,255,255,.5);margin:20px -15px 0 -15px;">
<div class="container">
<div class="row">
  <br>
  <br>
 <div class="col-md-4" style="font-size: 200px; text-align: center;">
 	<i class="fa fa-envelope-o"></i>
 </div>
 <div class='col-md-8'>
    <h3>New Message:</h2>
    <%= render 'form' %>
</div>
</div>
</div>
</div>

app/views/conversations/reply.js.erb
var $form = $("form#new_blog_comment");
<% if @comment.save %>
  $("#comments").append("<%= escape_javascript(render(@comment)) %>");
  $(".new-comment_<%= @comment.post.id %>").append("<%= escape_javascript(render('company_profiles/comments', comment: @comment)) %>");
  $(".counter_<%= @comment.post.id %>").text("Comment(<%= @comment.post.comments.count %>)");
  $form.get(0).reset();
  $("form#edit_post_"+"<%= @comment.post.id %>").get(0).reset();
<% else %>
  $form.html("<%= escape_javascript(render(partial:'form', locals: { post: @comment.post, comment: @comment })) %>");
<% end %>

app/views/conversations/sentbox.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= render "conversations/panel_message" %>
      <div class="col-sm-10">
        <h2 style="margin: 1px 0 2px 120px;">General Message <small>showing all message</small></h2>
        <br/>
        <div id="compose-message" hidden="true">
          <%= render "conversations/form" %>
        </div>
        <%= render "conversations/mail_sentbox" %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(e){
    $("#show-message").click(function(){
      $("#compose-message").toggle();
      e.preventDefault();
    });
  })
</script>

app/views/conversations/show.html.erb
<div class="row">
  <div id="primary" class="col-sm-12">
    <div class="content">
      <% current_user.mailbox.inbox.each do |conversation| %>
        <section class="post" >
         <div class="post-content new-comment_<%= conversation.id %> media" data-id="<%= conversation.id %>"></div>
          <% other_user = (conversation.messages.collect(&:sender) - [current_user]).first %>
          <% conversation.messages.limit(3).each do |message| %>
            <header class="entry-header">
              <% user = message.sender %>
              <% if user.is_a?(BusinessUser) %>
              <% url = user.avatar.blank? ? "business-avatar.png" : user.avatar.url %>
              <% else %>
              <% url = user.avatar.blank? ? "img/profile-placeholder.png" : user.avatar.url %>
              <% end %>
              <%= image_tag url , :height => "52", :width => "52", class: "entry-avatar" %>
              <h2 class="entry-title"><a href="#"><%= message.subject %></a></h2>
              <p class="entry-meta">
              Sent on <a class="entry-date" href="#"><%= message.created_at.strftime("%B %d, %Y")%></a> | From <a class="entry-author" href="#"><%= user.subdomain %></a> | Tags 
              <% ['tag1', 'tag2'].each do |tag| %>
                <a class="label label-danger" href="#"><%= tag %></a>
              <% end %>
              </p>
            </header>
            <div class="entry-description comment more"><%= message.body %></div>
            <hr>
          <% end %>
          <h5><small><%= link_to "View Full Conversation", conversation %></small></h5>
          <%= render 'inbox_reply_form', commentor: current_user, recipient: other_user, conversation: conversation, title: "Re : "+conversation.subject %>
        </section>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/sticky_post.html.erb
<div class="container">
  <h4><strong>New Sticky Post</strong></h4>
  <br /><br />
  <%# if current_user == @user %>
    <%= form_for Blogit::Post.new, url: post_save_path do |f| %>
      <div class="form-group">
        <%#= f.label :title, "Topic" %>
        <%= f.text_field :title, class: "form-control", :required => true, :placeholder=>"TOPIC" %>
      </div>
      <div class="form-group">
        <%#= f.label :title, "Tags" %>
        <%= f.text_field :tag_list, class: "form-control", :required => true, :placeholder=>"TAGS" %>
      </div>
      <div class="form-group">
        <%#= f.label :title, "Post Content" %>
        <%= f.text_area :body, class: "form-control", rows: "5", :required => true, :placeholder=>"CONTENT" %>
        <%= f.hidden_field :post_type, :value => "Sticky" %>
      </div>
      <%= f.submit "Create Sticky Post", class: "btn btn-success" %>
      <button type="reset" class="btn btn-warning post-cancel" id="cancel-post">Cancel</button>
    <% end %>
    <br>
  <%# elsif current_user.nil? %>
    <%#= link_to "Login", login_path, class: 'btn btn-primary' %>
    <%#= link_to "Register", register_path, class: 'btn btn-danger' %>
  <%# else %>
    <%#= render 'conversations/form', show_cancel: false %>
  <%# end %>
</div>