config/routes.rb
class WWWSubdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain == 'www')
  end
end

class Subdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain != 'www')
  end
end

SkyhqNew::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  authenticated :citizen do
    get '/' => 'blogit/posts#index'
  end

  # authenticated :super_admin do
  #   get '/' => 'blogit/posts#index'
  # end

  authenticated :business_user do
    get '/' => 'blogit/posts#index'
  end
  
  constraints(WWWSubdomain.new) do
    get '/' => 'general_pages#index'
  end

  constraints(Subdomain.new) do
    get '/' => Blogit::Engine
      # post "", to: "company_profiles#edit_post", as: "company_edit_post"
  end
  
  root :to => 'general_pages#index'

  match   "/post/save" => 'general_pages#save_post', :via => :post
  match   "/post/edit/:id" => 'general_pages#edit_post', :via => :put, as: "post_edit"

  post    "public/:id/tagline/", to: "company_profiles#save_tagline", as: "company_tagline"
  patch   "public/:id/edit/", to: "company_profiles#edit_post", as: "company_edit_post"
  delete  "public/:id", to: "general_pages#destroy_post", as: "delete_post"
  get "public", to: "blogit/posts#index"
  get '/get_citizens' => 'general_pages#get_citizen'
  get  '/home' => 'general_pages#index'
  get  '/about' => 'general_pages#about'
  get  '/contact' => 'general_pages#contact'
  get  '/faq' => 'general_pages#faq'
  get  '/testimonials' => 'general_pages#testimonials'
  get  '/pricing' => 'general_pages#pricing'
  get  '/services' => 'general_pages#services'
  get  '/tos' => 'general_pages#tos'
  post '/check-email' => 'general_pages#check_email'
  post '/check-subdomain' => 'general_pages#check_subdomain'
  get  '/edit_citizen_password' => 'blogit/posts#edit_citizen_password'
  post '/save_citizen_password' => 'blogit/posts#save_citizen_password'
  get  '/blog' => 'blogit/posts#index'

  post 'reply_comment/:post_id' => 'blogit/comments#create', :as => 'reply_comment'

  match '/posts/page/:page' => 'blogit/posts#index', :via => :get

  match '/posts' => 'blogit/posts#index', :via => :get

  get '/sticky_post' => 'conversations#sticky_post', :as => 'sticky_post'

  # get 'new_direct_message' => 'conversations#new_direct_message'
  # post 'direct_message' => 'conversations#direct_message', :as => 'direct_message'

  # post '/update_citizen_password' => 'blogit/posts#update_citizen_password'
  
  # match '/profile' => "company_profiles#admin_profile", :as => "admin_profile"
  # delete "/businesses/:business_id/managers/:id/delete", to: "managers#destroy", :as => "remove_manager"


  resources :manage_users
  
  resources :company_forums, :path => "comms" do
    resources :company_forum_topics do
      resources :forum_posts
    end
  end
  resources :company_docs, path: 'docs'

  resources :company_profiles

  resources :online_stores, :path => "orders" do
    resources :products
  end

  resources :categories, :path => "categories"

  resources :business_messengers, :path => "messengers"

  resources :locations do
    resources :managers 
    resources :employees
  end
  

  devise_for :citizens, :controllers => { 
    :omniauth_callbacks => "citizens/omniauth_callbacks",
    registrations: 'citizens/registrations',
    :sessions => 'user_authentications'
  }

  # devise_for :users

  devise_for :super_admins, controllers: { 
    registrations: 'super_admins/registrations'
    # ,
    # :sessions => 'user_authentications'
  }

  devise_for :business_users,:controllers => { 
    registrations: 'citizens/registrations'
  }

  devise_for :managers, skip: :sessions
  devise_for :staffs, skip: :sessions

  # devise_for :users, :controllers => { :sessions => :user_authentications, registrations: 'citizens/registrations'}
# devise_for :users, :skip => [:sessions]

  # devise_scope :super_admin do
  #   get "super_admins/login",    to: "devise/sessions#new"
  #   get "logout",   to: "devise/sessions#destroy"
  #   get "business/register", to: "devise/registrations#new"
  #   get "business/reset",    to: "devise/passwords#new"
  #   # get "business/profile", to: "devise/registrations#edit"
  # end

  devise_scope :citizen do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "reset",    to: "devise/passwords#new"
    get "profile", to: "devise/registrations#edit"
  end
  
  devise_scope :business_user do
    get "business/login", to: "devise/sessions#new", :as => 'business_login'
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "business/reset",    to: "devise/passwords#new"
    get "business/profile", to: "devise/registrations#edit", :as => 'business_profile'
  end

  get("/inbox/new/:super_admin_id", { :controller => "conversations", :action => 'new', :as => 'message_company'})

  get "sentbox", to: "conversations#sentbox", :as => 'sentbox'
  get "trashbox", to: "conversations#trashbox", :as => 'trashbox'
  
  resources :conversations, :path => "inbox", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :name, :price, :super_admin_id, :online_store_id


  # include Tire::Model::Search
  # include Tire::Model::Callbacks
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @online_store = OnlineStore.find_by_id(params[:id])
    @products = @online_store.products

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @online_store = OnlineStore.find_by_id(params[:online_store_id])
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @online_store = OnlineStore.find_by_id(params[:online_store_id])
    @super_admin = @online_store.super_admin
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @online_store = OnlineStore.find_by_id(params[:online_store_id])
    @product = @online_store.products.build(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to online_store_product_path(@online_store, @product), notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@online_store, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :business_user_id, :value => @super_admin.id %>
  </div>

  <div class="field">
    <%= f.hidden_field :online_store_id, :value => @online_store.id %>
  </div>

  <div class="field">
    <%= f.label :name, "Product Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
    <h1>Editing product</h1>
    <%= render 'form' %>
    <%= link_to 'Show', @product %> | <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container">
    <h1>Listing products</h1>
    <table>
        <tr>
            <th>
                Super admin
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
            </th>
            <th>
            </th>
            <th>
            </th>
        </tr>
        <% @products.each do |product| %>
        <tr>
            <td>
                <%= product.business_user_id %>
            </td>
            <td>
                <%= product.name %>
            </td>
            <td>
                <%= product.price %>
            </td>
            <td>
                <%= link_to 'Show', product %>
            </td>
            <td>
                <%= link_to 'Edit', edit_product_path(product) %>
            </td>
            <td>
                <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
        <% end %>
    </table>
    <br/>
    <%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<div class="container">
    <h1>New product</h1>
    <%= render 'form' %>
    <%= link_to 'Back', online_store_products_path(@online_store) %>
</div>

app/views/products/show.html.erb
<div class="container">
    <h3>
        <b>Name:</b>
        <%= @product.name %>
    </h3>
	<h3>
        <b>Price:</b>
        <%= @product.price %>
    </h3> 
    <%= link_to 'Edit', edit_online_store_product_path(@product) %> | <%= link_to 'Back', online_stores_path %>
</div>