config/routes.rb
class WWWSubdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain == 'www')
  end
end

class Subdomain
  def matches?(request)
    request.subdomain.present? and (request.subdomain != 'www')
  end
end

SkyhqNew::Application.routes.draw do

  # This line mounts Forem's routes at /forums by default.
  # This means, any requests to the /forums URL of your application will go to Forem::ForumsController#index.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Forem relies on it being the default of "forem"
  mount Forem::Engine, :at => '/forums'


  authenticated :citizen do
    get '/' => 'blogit/posts#index'
  end

  # authenticated :super_admin do
  #   get '/' => 'blogit/posts#index'
  # end

  authenticated :business_user do
    get '/' => 'blogit/posts#index'
  end
  
  constraints(WWWSubdomain.new) do
    get '/' => 'general_pages#index'
  end

  constraints(Subdomain.new) do
    get '/' => Blogit::Engine
      # post "", to: "company_profiles#edit_post", as: "company_edit_post"
  end
  
  root :to => 'general_pages#index'

  match   "/post/save" => 'general_pages#save_post', :via => :post
  match   "/post/edit/:id" => 'general_pages#edit_post', :via => :put, as: "post_edit"

  post    "public/:id/tagline/", to: "company_profiles#save_tagline", as: "company_tagline"
  patch   "public/:id/edit/", to: "company_profiles#edit_post", as: "company_edit_post"
  delete  "public/:id", to: "general_pages#destroy_post", as: "delete_post"
  get "public", to: "blogit/posts#index"
  get '/get_citizens' => 'general_pages#get_citizen'
  get  '/home' => 'general_pages#index'
  get  '/about' => 'general_pages#about'
  get  '/contact' => 'general_pages#contact'
  get  '/faq' => 'general_pages#faq'
  get  '/testimonials' => 'general_pages#testimonials'
  get  '/pricing' => 'general_pages#pricing'
  get  '/services' => 'general_pages#services'
  get  '/tos' => 'general_pages#tos'
  post '/check-email' => 'general_pages#check_email'
  post '/check-subdomain' => 'general_pages#check_subdomain'
  get  '/edit_citizen_password' => 'blogit/posts#edit_citizen_password'
  post '/save_citizen_password' => 'blogit/posts#save_citizen_password'
  get  '/blog' => 'blogit/posts#index'

  post 'reply_comment/:post_id' => 'blogit/comments#create', :as => 'reply_comment'

  match '/posts/page/:page' => 'blogit/posts#index', :via => :get

  match '/posts' => 'blogit/posts#index', :via => :get

  get '/sticky_post' => 'conversations#sticky_post', :as => 'sticky_post'

  # get 'new_direct_message' => 'conversations#new_direct_message'
  # post 'direct_message' => 'conversations#direct_message', :as => 'direct_message'

  # post '/update_citizen_password' => 'blogit/posts#update_citizen_password'
  
  # match '/profile' => "company_profiles#admin_profile", :as => "admin_profile"
  # delete "/businesses/:business_id/managers/:id/delete", to: "managers#destroy", :as => "remove_manager"


  resources :manage_users
  
  resources :company_forums, :path => "comms" do
    resources :company_forum_topics do
      resources :forum_posts
    end
  end
  resources :company_docs, path: 'docs'

  resources :company_profiles

  resources :online_stores, :path => "orders" do
    resources :products
  end

  resources :categories, :path => "categories"

  resources :business_messengers, :path => "messengers"

  resources :locations do
    resources :managers 
    resources :employees
  end
  

  devise_for :citizens, :controllers => { 
    :omniauth_callbacks => "citizens/omniauth_callbacks",
    registrations: 'citizens/registrations',
    :sessions => 'user_authentications'
  }

  # devise_for :users

  devise_for :super_admins, controllers: { 
    registrations: 'super_admins/registrations'
    # ,
    # :sessions => 'user_authentications'
  }

  devise_for :business_users,:controllers => { 
    registrations: 'citizens/registrations'
  }

  devise_for :managers, skip: :sessions
  devise_for :staffs, skip: :sessions

  # devise_for :users, :controllers => { :sessions => :user_authentications, registrations: 'citizens/registrations'}
# devise_for :users, :skip => [:sessions]

  # devise_scope :super_admin do
  #   get "super_admins/login",    to: "devise/sessions#new"
  #   get "logout",   to: "devise/sessions#destroy"
  #   get "business/register", to: "devise/registrations#new"
  #   get "business/reset",    to: "devise/passwords#new"
  #   # get "business/profile", to: "devise/registrations#edit"
  # end

  devise_scope :citizen do
    get "login",    to: "devise/sessions#new"
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "reset",    to: "devise/passwords#new"
    get "profile", to: "devise/registrations#edit"
  end
  
  devise_scope :business_user do
    get "business/login", to: "devise/sessions#new", :as => 'business_login'
    get "logout",   to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "business/reset",    to: "devise/passwords#new"
    get "business/profile", to: "devise/registrations#edit", :as => 'business_profile'
  end

  get("/inbox/new/:super_admin_id", { :controller => "conversations", :action => 'new', :as => 'message_company'})

  get "sentbox", to: "conversations#sentbox", :as => 'sentbox'
  get "trashbox", to: "conversations#trashbox", :as => 'trashbox'
  
  resources :conversations, :path => "inbox", only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/views/layouts/partials/_footerunify.html.erb
<!--=== Footer ===-->
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 md-margin-bottom-40">
                <!-- About -->
                <div class="headline"><h2>About</h2></div>  
                <p class="margin-bottom-25 md-margin-bottom-40">SkyHQ is an incredibly beautiful responsive Bootstrap Template for corporate and creative professionals.</p>    
            </div><!--/col-md-4-->  
            <div class="col-md-4">
                <!-- Monthly Newsletter -->
                <div class="headline"><h2>Monthly Newsletter</h2></div> 
                <p>Subscribe to our newsletter and stay up to date with the latest news and deals!</p>
                <form class="footer-subsribe">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Email Address">                            
                        <span class="input-group-btn">
                            <button class="btn-u" type="button">Subscribe</button>
                        </span>
                    </div><!-- /input-group -->                    
                </form>      
                            </div><!--/col-md-4-->
            <div class="col-md-4">
                <!-- Stay Connected -->
                <div class="headline"><h2>Stay Connected</h2></div> 
                <ul class="social-icons">
                    <li><a href="#" data-original-title="Feed" class="social_rss"></a></li>
                    <li><a href="#" data-original-title="Facebook" class="social_facebook"></a></li>
                    <li><a href="#" data-original-title="Twitter" class="social_twitter"></a></li>
                    <li><a href="#" data-original-title="Goole Plus" class="social_googleplus"></a></li>
                    <li><a href="#" data-original-title="Pinterest" class="social_pintrest"></a></li>
                    <li><a href="#" data-original-title="Linkedin" class="social_linkedin"></a></li>
                    <li><a href="#" data-original-title="Vimeo" class="social_vimeo"></a></li>
                </ul>
            </div><!--/col-md-4-->
        </div><!--/row-->   
    </div><!--/container--> 
</div><!--/footer-->    
<!--=== End Footer ===-->

<!--=== Copyright ===-->
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-md-6">                      
                <p class="copyright-space">
                    2013 &copy; SkyHQ. ALL Rights Reserved. 
                    <a href="/tos">Terms of Service</a> | <a href="/contact">Contact Us</a> 
                </p>
            </div>
            <div class="col-md-6">  
                <a href="index.html">
                    <%= image_tag 'img/logo2-default.png', class: 'pull-right', id: 'logo-footer' %>
                </a>
            </div>
        </div><!--/row-->
    </div><!--/container--> 
</div><!--/copyright--> 
<!--=== End Copyright ===-->

app/views/layouts/partials/_headersmartadmin.html.erb
<!-- HEADER --> 
<div class="hide-body">
<header id="header">
  <hgroup>
    <% if current_user %>
      <% unless current_user.subdomain != request.subdomain %>
        <div>
          <div class="pull-left">
            <span>
              <div class="btn-group pull-left" style="min-width: 200px;margin-top: 5px;">
                <a href="#" data-toggle="dropdown" style="font-size: 26px;margin-left: 10px;margin-top: 10px;color:#333;">
                  <strong>HQ</strong>
                </a>
            
                <ul class="dropdown-menu" style="width: auto;">
                  <li>
                    <a href="#" id="show-shortcut">
                      <%= current_user.subdomain.capitalize rescue "" %> <i class="fa fa-angle-down"></i>
                    </a>
                  </li>
                  <% if current_citizen %>
                    <li class="" style=""><a href="<%= public_path %>" title="Blog"><i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Blog</span></a></li>
                  <% end %>
                  <% if current_super_admin %>
                    <li>
                      <a href="<%= blog_path %>" title="Blog"><i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Blog</span></a></li>
                  <% end %>
                  <% if current_user %>
                    <li class="">
                      <a href="<%= conversations_path %>">
                        <i class="fa fa-lg fa-fw fa-inbox"></i>
                        <span class="menu-item-parent">Inbox</span>
                        <span class="badge pull-right inbox-badge"></span>
                      </a>
                    </li>
                    <li>
                      <a href="<%= new_conversation_path %>">
                        <i class="fa fa-lg fa-fw fa-envelope-o"></i>
                        <span class="menu-item-parent">Compose Message</span>
                        <span class="badge pull-right inbox-badge"></span>
                      </a>    
                    </li>
                  <%end%>
                  <% if current_super_admin || current_business_user.is_a?(SuperAdmin) %>
                    <li><a href="<%= locations_path %>" title="Locations HQ"><i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Locations HQ</span></a></li>
                    <li><a href="<%= online_stores_path %>"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i>  <span class="menu-item-parent">Orders HQ</span></a></li>
                    <li><a href="<%= company_forums_path %>"><i class="fa fa-lg fa-fw fa-table"></i>  <span class="menu-item-parent">Communications HQ</span></a></li>
                      <li><a href="<%= public_path %>"><i class="fa fa-lg fa-fw fa-pencil-square-o"></i>  <span class="menu-item-parent">Public HQ</span></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Team HQ</span></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Vendors HQ</span></a></li>
                    <li><a href="#"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Customers HQ</span></a></li>
                    <li><a href="<%= company_docs_path %>"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Docs HQ</span></a></li>
                    <li><a href="<%= manage_users_path %>"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Manage Users</span></a></li>
                  <% end %>
                </ul>
              </div> 
            </span>
          </div>
        </div>
      <% end %>
    <% end %>

    <h1 class="site-title text-center" style="font-size: 25px; padding-top: 10px;">
      <%# if !current_user || current_user.subdomain != request.subdomain %>
        <span id="logo-header">
          <center>
            <a href="<%= root_path %>">
              <%#= image_tag 'img/logo.png', alt: "SmartAdmin" %>
              <strong style="color: #235A9F;">
                <%= request.subdomain.capitalize %>
              </strong>
            </a>
          </center>
        </span>
      <%# else %>
        <!-- <span id="logo" style="margin-top: -1px;margin-left: -125px;">
          <a href="<%= root_path %>">
            <%= image_tag 'img/logo.png', alt: "SmartAdmin" %>
          </a>
        </span> -->
      <%# end %>

      <% if current_user %>
        <% if current_user.subdomain == request.subdomain or current_user %>
          <div class="btn-group pull-right" style="background: none;">
            <a href="#" data-toggle="dropdown">
              <%= image_tag current_user_picture , :height => "30", :width => "30", class: "entry-avatar" %>
            </a>
            <ul class="dropdown-menu" style="width: 20px;">
              <li>
                <% if current_super_admin %>
                  <%= link_to "Setting", business_profile_path, :style => "text-align: left" %>
                <% else %>
                  <%= link_to "Setting", edit_citizen_registration_path, :style => "text-align: left" %>
                <% end %>
              </li>
              <li>
                <%= link_to "Logout", logout_path, :style => "text-align: left" %>
              </li>
            </ul>
          </div>
        <% end %>
      <% end %>
    </h1>
  </hgroup>

</header>
<!-- END HEADER -->

        <!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<!-- style="height: 100%; top: 0; -->
<aside id="left-panel" style="top: 0; display:none;">

</aside>
<!-- END NAVIGATION -->
</div>

app/views/layouts/partials/_headerunify.html.erb
<!--=== Style Switcher ===-->
<!--
<i class="style-switcher-btn icon-cogs hidden-xs"></i>
<div class="style-switcher">
    <div class="theme-close"><i class="icon-remove"></i></div>
    <div class="theme-heading">Theme Colors</div>
    <ul class="list-unstyled">
        <li class="theme-default theme-active" data-style="default" data-header="light"></li>
        <li class="theme-blue" data-style="blue" data-header="light"></li>
        <li class="theme-orange" data-style="orange" data-header="light"></li>
        <li class="theme-red" data-style="red" data-header="light"></li>
        <li class="theme-light last" data-style="light" data-header="light"></li>
    </ul>
    <div style="margin-bottom:18px;"></div>
    <div class="theme-heading">Layouts</div>
    <div class="text-center">
        <a href="#" class="btn-u btn-u-green btn-block active-switcher-btn wide-layout-btn">Wide</a>
        <a href="#" class="btn-u btn-u-green btn-block boxed-layout-btn">Boxed</a>
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<!--=== Top ===-->    
<div class="top">
    <div class="container">         
        <ul class="loginbar pull-right">
            <li><a href="/faq">Help</a></li>  
            <li class="devider"></li>   
            <li><%= link_to "Login", login_path %></li>
			<li class="devider"></li>   
			<li><%= link_to "Register", register_path %></li>
        </ul>
    </div>      
</div><!--/top-->
<!--=== End Top ===-->    

<!--=== Header ===-->    
<div class="header">
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/home">
                    <%= image_tag 'img/logo1-default.png', id: 'logo-header', alt: 'Logo' %>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="/home" data-delay="0" data-close-others="false">
                            Home
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="/about" data-delay="0" data-close-others="false">
                            About
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">
                            Features
                            <i class="icon-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/pricing">Pricing</a></li>
                            <li><a href="/testimonials">Testimonials</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="/contact" data-hover="dropdown" data-delay="0" data-close-others="false">
                            Contact
                        </a>
                    </li>                    
                    <!-- <li class="hidden-sm"><a class="search"><i class="icon-search search-btn"></i></a></li> -->
                </ul>
                <div class="search-open">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">
                            <button class="btn-u" type="button">Go</button>
                        </span>
                    </div><!-- /input-group -->
                </div>                
            </div><!-- /navbar-collapse -->
        </div>    
    </div>    
</div><!--/header-->
<!--=== End Header ===-->    